-- =============================================================================
-- 015_identity.sql
-- Sign-in store (13-security CR-03, ADR-0016, 02-architecture §4.2.1/§10.1, DECISIONS D-K7):
-- ASP.NET Core Identity credentials, BFF sessions, one-time tokens, OpenIddict entities and the
-- data-protection key ring. Sign-in happens BEFORE a tenant context exists (SEC-RLS-06), so these
-- tables are tenant-less, have NO row-level security and are reachable only by app_user (never by
-- app_readonly / app_ops). Secrets are stored hashed or encrypted only. Not audited in audit.row_change
-- (security events go to audit.security_event).
--
-- OpenIddict tables follow the OpenIddict.EntityFrameworkCore 6.x entity model with the snake_case naming
-- convention (EFCore.NamingConventions). SQL-first (ADR-0014): when the library is upgraded, generate the
-- model script (`dotnet ef migrations script` on the identity DbContext) and diff it against this file.
-- =============================================================================
\set ON_ERROR_STOP on
SET ROLE app_owner;

CREATE TABLE identity.user_credential (
    user_id                uuid PRIMARY KEY REFERENCES platform.app_user (id),
    password_hash          text,                              -- ASP.NET Core Identity PasswordHasher v3 (PBKDF2); NULL = external login only
    security_stamp         uuid NOT NULL DEFAULT gen_random_uuid(),   -- changes invalidate cookies / sessions
    lockout_end            timestamptz,
    access_failed_count    integer NOT NULL DEFAULT 0 CHECK (access_failed_count >= 0),
    totp_secret_protected  bytea,                             -- TOTP secret encrypted with the data-protection key ring
    last_totp_step         bigint,                            -- replay protection (RFC 6238 time step already used)
    recovery_code_hashes   text[],                            -- hashed one-time recovery codes
    password_changed_at    timestamptz,
    email_confirmed_at     timestamptz,                       -- NULL = e-mail not yet verified (13 §5.3, CR-03; REVIEW-readiness B-03)
    created_at             timestamptz NOT NULL DEFAULT now(),
    updated_at             timestamptz
);
COMMENT ON TABLE identity.user_credential IS 'Local credentials of a platform.app_user (ASP.NET Core Identity UserManager store, simplified): password hash, security stamp, lockout, protected TOTP secret, hashed recovery codes (13 SEC-ID). Tenant-less, no RLS.';

CREATE TABLE identity.user_session (
    id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    sid_hash           bytea NOT NULL UNIQUE CHECK (octet_length(sid_hash) = 32),   -- SHA-256 of the session id in the cookie
    user_id            uuid NOT NULL REFERENCES platform.app_user (id),
    ticket_ciphertext  bytea NOT NULL,                       -- BFF authentication ticket, data-protection encrypted
    amr                text[] NOT NULL DEFAULT '{}',         -- authentication methods (pwd, otp, ...)
    auth_time          timestamptz NOT NULL,
    recent_auth_at     timestamptz,                          -- step-up re-authentication (13 §5.7)
    active_tenant_id   uuid REFERENCES platform.tenant (id), -- tenant chosen after sign-in (named so that tenant RLS does not apply)
    client_ip          inet,
    user_agent         text,
    created_at         timestamptz NOT NULL DEFAULT now(),
    expires_at         timestamptz NOT NULL,
    revoked_at         timestamptz,
    CHECK (expires_at > created_at)
);
CREATE INDEX ix_user_session__user ON identity.user_session (user_id) WHERE revoked_at IS NULL;
CREATE INDEX ix_user_session__tenant ON identity.user_session (active_tenant_id) WHERE active_tenant_id IS NOT NULL;
CREATE INDEX ix_user_session__expires ON identity.user_session (expires_at);
COMMENT ON TABLE identity.user_session IS 'Server-side BFF session store (02 §4.2.1): lookup by sid hash; revocation by user / security stamp. Tenant-less, no RLS.';

CREATE TABLE identity.one_time_token (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    token_hash    bytea NOT NULL UNIQUE CHECK (octet_length(token_hash) = 32),
    purpose       text NOT NULL CHECK (purpose IN ('EMAIL_CONFIRMATION','PASSWORD_RESET','EMAIL_CHANGE','MFA_RESET')),
    user_id       uuid REFERENCES platform.app_user (id),
    email         text CHECK (email = lower(email)),
    expires_at    timestamptz NOT NULL,
    consumed_at   timestamptz,
    created_at    timestamptz NOT NULL DEFAULT now(),
    CHECK (user_id IS NOT NULL OR email IS NOT NULL),
    CHECK (expires_at > created_at)
);
CREATE INDEX ix_one_time_token__user ON identity.one_time_token (user_id) WHERE user_id IS NOT NULL;
COMMENT ON TABLE identity.one_time_token IS 'Hashed one-time tokens (e-mail confirmation, password reset, ...). Single use (consumed_at). Tenant invitations use platform.tenant_invitation.';

CREATE TABLE identity.data_protection_key (
    id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    friendly_name  text,
    xml            text
);
COMMENT ON TABLE identity.data_protection_key IS 'ASP.NET Core Data Protection key ring (Microsoft.AspNetCore.DataProtection.EntityFrameworkCore DataProtectionKey); key XML is encrypted at rest by the configured key-encryption certificate / KMS.';

-- OpenIddict entities --------------------------------------------------------------------------------
CREATE TABLE identity.oidc_application (
    id                        text PRIMARY KEY,
    application_type          text,
    client_id                 text UNIQUE,
    client_secret             text,                         -- hashed by OpenIddict
    client_type               text,
    concurrency_token         text,
    consent_type              text,
    display_name              text,
    display_names             text,
    json_web_key_set          text,
    permissions               text,
    post_logout_redirect_uris text,
    properties                text,
    redirect_uris             text,
    requirements              text,
    settings                  text
);
COMMENT ON TABLE identity.oidc_application IS 'OpenIddict application (OpenIddictEntityFrameworkCoreApplication). Integration clients of a tenant are mapped through platform.integration_client.oidc_client_id.';

CREATE TABLE identity.oidc_authorization (
    id                 text PRIMARY KEY,
    application_id     text REFERENCES identity.oidc_application (id),
    concurrency_token  text,
    creation_date      timestamptz,
    properties         text,
    scopes             text,
    status             text,
    subject            text,
    type               text
);
CREATE INDEX ix_oidc_authorization__app ON identity.oidc_authorization (application_id, status, subject, type);
COMMENT ON TABLE identity.oidc_authorization IS 'OpenIddict authorization (OpenIddictEntityFrameworkCoreAuthorization).';

CREATE TABLE identity.oidc_scope (
    id                 text PRIMARY KEY,
    concurrency_token  text,
    description        text,
    descriptions       text,
    display_name       text,
    display_names      text,
    name               text UNIQUE,
    properties         text,
    resources          text
);
COMMENT ON TABLE identity.oidc_scope IS 'OpenIddict scope (OpenIddictEntityFrameworkCoreScope).';

CREATE TABLE identity.oidc_token (
    id                 text PRIMARY KEY,
    application_id     text REFERENCES identity.oidc_application (id),
    authorization_id   text REFERENCES identity.oidc_authorization (id),
    concurrency_token  text,
    creation_date      timestamptz,
    expiration_date    timestamptz,
    payload            text,
    properties         text,
    redemption_date    timestamptz,
    reference_id       text UNIQUE,                        -- hashed reference token id
    status             text,
    subject            text,
    type               text
);
CREATE INDEX ix_oidc_token__app ON identity.oidc_token (application_id, status, subject, type);
CREATE INDEX ix_oidc_token__authorization ON identity.oidc_token (authorization_id);
COMMENT ON TABLE identity.oidc_token IS 'OpenIddict token (OpenIddictEntityFrameworkCoreToken); pruned by the OpenIddict Quartz job.';

-- Privileges: the web/worker role only; no RLS (tenant-less sign-in data).
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA identity TO app_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA identity TO app_user;
