namespace Erp.GeneralLedger.Contracts.Posting;

/// <summary>Where a G/L line's account came from (decides which account rules apply, 05-posting-engine.md §5.1).</summary>
public enum LineOrigin
{
    /// <summary>Chosen by the user: <c>direct_posting</c> must be true (BR-PST-15).</summary>
    UserEntered = 0,

    /// <summary>Derived from setup (VAT account, receivables control account): direct posting is not required.</summary>
    SystemDerived = 1,

    /// <summary>Generated by the system (reversal, year-end close).</summary>
    SystemGenerated = 2,
}
